name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
    
    - name: Configure with CMake
      run: |
        mkdir -p frontend/build
        cd frontend/build
        cmake ..
    
    - name: Build with Make
      run: |
        cd frontend/build
        make
    
    - name: Run Tests
      run: |
        cd frontend/build
        source run.sh
